version: '3.9'

services:
  # cmak
  cmak:
    container_name: cmak
    hostname: cmak
    image: waisy/cmak:3.0.0.5-v1
    ports:
      - "9000:9000"
    volumes:
      - ./conf/application.conf:/etc/cmak/application.conf
    restart: always
